TrajectoryPlannerROS:
  max_vel_x: 1.0
  min_vel_x: 0.2
  max_vel_theta: 1.0
  min_in_place_vel_theta: 0.1
  yaw_goal_tolerance: 0.1
  xy_goal_tolerance: 1.0
  latch_xy_goal_tolerance: false
  meter_scoring: true
  sim_time: 1.0  # default is 1.0, min_vel*sim_period < 2*xy_goal_tolerance

  acc_lim_theta: 2.0 #3.2
  acc_lim_x: 2.0 #2.5
  acc_lim_y: 2.0 #2.5
 
  holonomic_robot: false

  dwa: true
